name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Executing remote ssh commands to deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Entra na pasta do projeto e atualiza o código
            cd /root/crm-mdr
            git reset --hard HEAD
            git pull origin main
            
            # Sincroniza o arquivo .env (opcional, se você quiser gerenciar via git)
            # cp .env.example .env 
            
            # Reconstrói apenas o container da aplicação no docker-compose da infra
            cd /root/crm-mdr
            docker-compose -f docker-compose.infra.yml up -d --build app || docker compose -f docker-compose.infra.yml up -d --build app
            
            # Limpa imagens antigas para economizar espaço
            docker image prune -f
